//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.Seguridad.Talentos.SI.WS.LoginReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/soap/servidor.php", ConfigurationName="LoginReference.miWebServicePort")]
    public interface miWebServicePort {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/soap/servidor.php#generallave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string generallave(string palabra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/soap/servidor.php#encriptar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string encriptar(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/soap/servidor.php#desencriptar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string desencriptar(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/soap/servidor.php#anti_injection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string anti_injection(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/soap/servidor.php#validaremail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string validaremail(string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/soap/servidor.php#Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPC.Seguridad.Talentos.SI.WS.LoginReference.Respuesta Login(UPC.Seguridad.Talentos.SI.WS.LoginReference.Usuario user);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://localhost/soap/servidor.php")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private int sexoField;
        
        private string emailField;
        
        private string pwdField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        public int sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
                this.RaisePropertyChanged("sexo");
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        public string pwd {
            get {
                return this.pwdField;
            }
            set {
                this.pwdField = value;
                this.RaisePropertyChanged("pwd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://localhost/soap/servidor.php")]
    public partial class Respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Usuario usuarioField;
        
        private string mensajeField;
        
        private int valorField;
        
        /// <remarks/>
        public Usuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public int valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface miWebServicePortChannel : UPC.Seguridad.Talentos.SI.WS.LoginReference.miWebServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class miWebServicePortClient : System.ServiceModel.ClientBase<UPC.Seguridad.Talentos.SI.WS.LoginReference.miWebServicePort>, UPC.Seguridad.Talentos.SI.WS.LoginReference.miWebServicePort {
        
        public miWebServicePortClient() {
        }
        
        public miWebServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public miWebServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public miWebServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public miWebServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string generallave(string palabra) {
            return base.Channel.generallave(palabra);
        }
        
        public string encriptar(string cadena) {
            return base.Channel.encriptar(cadena);
        }
        
        public string desencriptar(string cadena) {
            return base.Channel.desencriptar(cadena);
        }
        
        public string anti_injection(string sql) {
            return base.Channel.anti_injection(sql);
        }
        
        public string validaremail(string valor) {
            return base.Channel.validaremail(valor);
        }
        
        public UPC.Seguridad.Talentos.SI.WS.LoginReference.Respuesta Login(UPC.Seguridad.Talentos.SI.WS.LoginReference.Usuario user) {
            return base.Channel.Login(user);
        }
    }
}
