//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace Talentos_Master.ReportesReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoFinalBE", Namespace="http://tempuri.org/")]
    public partial class ResultadoFinalBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int Participante_IdField;
        
        private string NombreParticipanteField;
        
        private string ApellidoPaternoField;
        
        private string ApellidoMaternoField;
        
        private string DNIField;
        
        private string SexoField;
        
        private string FechaNacimientoField;
        
        private string NivelInstruccionField;
        
        private string CargoEmpresaField;
        
        private string CorreoElectronicoField;
        
        private string InstitucionField;
        
        private System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> TalentosField;
        
        private System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTalentosMasDesarrolladosField;
        
        private System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTalentosMenosDesarrolladosField;
        
        private System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTalentosIntermedioDesarrolladosField;
        
        private System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTEMasDesarrolladosField;
        
        private System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTEMenosDesarrolladosField;
        
        private System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstVirtudesField;
        
        private System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTalentosTotalesField;
        
        private double PuntajeField;
        
        private string CodigoEvaluacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Participante_Id {
            get {
                return this.Participante_IdField;
            }
            set {
                if ((this.Participante_IdField.Equals(value) != true)) {
                    this.Participante_IdField = value;
                    this.RaisePropertyChanged("Participante_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NombreParticipante {
            get {
                return this.NombreParticipanteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreParticipanteField, value) != true)) {
                    this.NombreParticipanteField = value;
                    this.RaisePropertyChanged("NombreParticipante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DNI {
            get {
                return this.DNIField;
            }
            set {
                if ((object.ReferenceEquals(this.DNIField, value) != true)) {
                    this.DNIField = value;
                    this.RaisePropertyChanged("DNI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaNacimientoField, value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string NivelInstruccion {
            get {
                return this.NivelInstruccionField;
            }
            set {
                if ((object.ReferenceEquals(this.NivelInstruccionField, value) != true)) {
                    this.NivelInstruccionField = value;
                    this.RaisePropertyChanged("NivelInstruccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string CargoEmpresa {
            get {
                return this.CargoEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoEmpresaField, value) != true)) {
                    this.CargoEmpresaField = value;
                    this.RaisePropertyChanged("CargoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Institucion {
            get {
                return this.InstitucionField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitucionField, value) != true)) {
                    this.InstitucionField = value;
                    this.RaisePropertyChanged("Institucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> Talentos {
            get {
                return this.TalentosField;
            }
            set {
                if ((object.ReferenceEquals(this.TalentosField, value) != true)) {
                    this.TalentosField = value;
                    this.RaisePropertyChanged("Talentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTalentosMasDesarrollados {
            get {
                return this.lstTalentosMasDesarrolladosField;
            }
            set {
                if ((object.ReferenceEquals(this.lstTalentosMasDesarrolladosField, value) != true)) {
                    this.lstTalentosMasDesarrolladosField = value;
                    this.RaisePropertyChanged("lstTalentosMasDesarrollados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTalentosMenosDesarrollados {
            get {
                return this.lstTalentosMenosDesarrolladosField;
            }
            set {
                if ((object.ReferenceEquals(this.lstTalentosMenosDesarrolladosField, value) != true)) {
                    this.lstTalentosMenosDesarrolladosField = value;
                    this.RaisePropertyChanged("lstTalentosMenosDesarrollados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTalentosIntermedioDesarrollados {
            get {
                return this.lstTalentosIntermedioDesarrolladosField;
            }
            set {
                if ((object.ReferenceEquals(this.lstTalentosIntermedioDesarrolladosField, value) != true)) {
                    this.lstTalentosIntermedioDesarrolladosField = value;
                    this.RaisePropertyChanged("lstTalentosIntermedioDesarrollados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTEMasDesarrollados {
            get {
                return this.lstTEMasDesarrolladosField;
            }
            set {
                if ((object.ReferenceEquals(this.lstTEMasDesarrolladosField, value) != true)) {
                    this.lstTEMasDesarrolladosField = value;
                    this.RaisePropertyChanged("lstTEMasDesarrollados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTEMenosDesarrollados {
            get {
                return this.lstTEMenosDesarrolladosField;
            }
            set {
                if ((object.ReferenceEquals(this.lstTEMenosDesarrolladosField, value) != true)) {
                    this.lstTEMenosDesarrolladosField = value;
                    this.RaisePropertyChanged("lstTEMenosDesarrollados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstVirtudes {
            get {
                return this.lstVirtudesField;
            }
            set {
                if ((object.ReferenceEquals(this.lstVirtudesField, value) != true)) {
                    this.lstVirtudesField = value;
                    this.RaisePropertyChanged("lstVirtudes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.TalentoComplexBE> lstTalentosTotales {
            get {
                return this.lstTalentosTotalesField;
            }
            set {
                if ((object.ReferenceEquals(this.lstTalentosTotalesField, value) != true)) {
                    this.lstTalentosTotalesField = value;
                    this.RaisePropertyChanged("lstTalentosTotales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public double Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((this.PuntajeField.Equals(value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string CodigoEvaluacion {
            get {
                return this.CodigoEvaluacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoEvaluacionField, value) != true)) {
                    this.CodigoEvaluacionField = value;
                    this.RaisePropertyChanged("CodigoEvaluacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TalentoComplexBE", Namespace="http://tempuri.org/")]
    public partial class TalentoComplexBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTalentoField;
        
        private int idTendenciaField;
        
        private int idTipoTalentoField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string tendenciaField;
        
        private string tipoTalentoField;
        
        private string imageField;
        
        private bool SeleccionadoField;
        
        private int Buzon_IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idTalento {
            get {
                return this.idTalentoField;
            }
            set {
                if ((this.idTalentoField.Equals(value) != true)) {
                    this.idTalentoField = value;
                    this.RaisePropertyChanged("idTalento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idTendencia {
            get {
                return this.idTendenciaField;
            }
            set {
                if ((this.idTendenciaField.Equals(value) != true)) {
                    this.idTendenciaField = value;
                    this.RaisePropertyChanged("idTendencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int idTipoTalento {
            get {
                return this.idTipoTalentoField;
            }
            set {
                if ((this.idTipoTalentoField.Equals(value) != true)) {
                    this.idTipoTalentoField = value;
                    this.RaisePropertyChanged("idTipoTalento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string tendencia {
            get {
                return this.tendenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.tendenciaField, value) != true)) {
                    this.tendenciaField = value;
                    this.RaisePropertyChanged("tendencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tipoTalento {
            get {
                return this.tipoTalentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoTalentoField, value) != true)) {
                    this.tipoTalentoField = value;
                    this.RaisePropertyChanged("tipoTalento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool Seleccionado {
            get {
                return this.SeleccionadoField;
            }
            set {
                if ((this.SeleccionadoField.Equals(value) != true)) {
                    this.SeleccionadoField = value;
                    this.RaisePropertyChanged("Seleccionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int Buzon_Id {
            get {
                return this.Buzon_IdField;
            }
            set {
                if ((this.Buzon_IdField.Equals(value) != true)) {
                    this.Buzon_IdField = value;
                    this.RaisePropertyChanged("Buzon_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuadroResultadoBE", Namespace="http://tempuri.org/")]
    public partial class CuadroResultadoBE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CuadroResultado_IdField;
        
        private string TextoField;
        
        private int Talento_IdField;
        
        private string TalentoField;
        
        private int Tendencia_IdField;
        
        private string TendenciaField;
        
        private int TipoTalento_IdField;
        
        private bool SeleccionadoField;
        
        private int TipoDesarrolloField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CuadroResultado_Id {
            get {
                return this.CuadroResultado_IdField;
            }
            set {
                if ((this.CuadroResultado_IdField.Equals(value) != true)) {
                    this.CuadroResultado_IdField = value;
                    this.RaisePropertyChanged("CuadroResultado_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Talento_Id {
            get {
                return this.Talento_IdField;
            }
            set {
                if ((this.Talento_IdField.Equals(value) != true)) {
                    this.Talento_IdField = value;
                    this.RaisePropertyChanged("Talento_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Talento {
            get {
                return this.TalentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TalentoField, value) != true)) {
                    this.TalentoField = value;
                    this.RaisePropertyChanged("Talento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Tendencia_Id {
            get {
                return this.Tendencia_IdField;
            }
            set {
                if ((this.Tendencia_IdField.Equals(value) != true)) {
                    this.Tendencia_IdField = value;
                    this.RaisePropertyChanged("Tendencia_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Tendencia {
            get {
                return this.TendenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.TendenciaField, value) != true)) {
                    this.TendenciaField = value;
                    this.RaisePropertyChanged("Tendencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int TipoTalento_Id {
            get {
                return this.TipoTalento_IdField;
            }
            set {
                if ((this.TipoTalento_IdField.Equals(value) != true)) {
                    this.TipoTalento_IdField = value;
                    this.RaisePropertyChanged("TipoTalento_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Seleccionado {
            get {
                return this.SeleccionadoField;
            }
            set {
                if ((this.SeleccionadoField.Equals(value) != true)) {
                    this.SeleccionadoField = value;
                    this.RaisePropertyChanged("Seleccionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int TipoDesarrollo {
            get {
                return this.TipoDesarrolloField;
            }
            set {
                if ((this.TipoDesarrolloField.Equals(value) != true)) {
                    this.TipoDesarrolloField = value;
                    this.RaisePropertyChanged("TipoDesarrollo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportesReference.wsReporteSoap")]
    public interface wsReporteSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Resultado", ReplyAction="*")]
        System.IAsyncResult BeginResultado(Talentos_Master.ReportesReference.ResultadoRequest request, System.AsyncCallback callback, object asyncState);
        
        Talentos_Master.ReportesReference.ResultadoResponse EndResultado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CargarResultadosMasivos", ReplyAction="*")]
        System.IAsyncResult BeginCargarResultadosMasivos(Talentos_Master.ReportesReference.CargarResultadosMasivosRequest request, System.AsyncCallback callback, object asyncState);
        
        Talentos_Master.ReportesReference.CargarResultadosMasivosResponse EndCargarResultadosMasivos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/EnviarMailResultado", ReplyAction="*")]
        System.IAsyncResult BeginEnviarMailResultado(Talentos_Master.ReportesReference.EnviarMailResultadoRequest request, System.AsyncCallback callback, object asyncState);
        
        Talentos_Master.ReportesReference.EnviarMailResultadoResponse EndEnviarMailResultado(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CalcularReporte", ReplyAction="*")]
        System.IAsyncResult BeginCalcularReporte(Talentos_Master.ReportesReference.CalcularReporteRequest request, System.AsyncCallback callback, object asyncState);
        
        Talentos_Master.ReportesReference.CalcularReporteResponse EndCalcularReporte(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CuadroResultadoListar", ReplyAction="*")]
        System.IAsyncResult BeginCuadroResultadoListar(Talentos_Master.ReportesReference.CuadroResultadoListarRequest request, System.AsyncCallback callback, object asyncState);
        
        Talentos_Master.ReportesReference.CuadroResultadoListarResponse EndCuadroResultadoListar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ResultadosParticipantesImportar", ReplyAction="*")]
        System.IAsyncResult BeginResultadosParticipantesImportar(Talentos_Master.ReportesReference.ResultadosParticipantesImportarRequest request, System.AsyncCallback callback, object asyncState);
        
        Talentos_Master.ReportesReference.ResultadosParticipantesImportarResponse EndResultadosParticipantesImportar(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Resultado", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.ResultadoRequestBody Body;
        
        public ResultadoRequest() {
        }
        
        public ResultadoRequest(Talentos_Master.ReportesReference.ResultadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Talentos_Master.ReportesReference.ResultadoFinalBE obj;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Talentos_Master.ReportesReference.TalentoComplexBE tal;
        
        public ResultadoRequestBody() {
        }
        
        public ResultadoRequestBody(Talentos_Master.ReportesReference.ResultadoFinalBE obj, Talentos_Master.ReportesReference.TalentoComplexBE tal) {
            this.obj = obj;
            this.tal = tal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.ResultadoResponseBody Body;
        
        public ResultadoResponse() {
        }
        
        public ResultadoResponse(Talentos_Master.ReportesReference.ResultadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ResultadoResponseBody {
        
        public ResultadoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarResultadosMasivosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarResultadosMasivos", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.CargarResultadosMasivosRequestBody Body;
        
        public CargarResultadosMasivosRequest() {
        }
        
        public CargarResultadosMasivosRequest(Talentos_Master.ReportesReference.CargarResultadosMasivosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CargarResultadosMasivosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.ResultadoFinalBE> lstResultados;
        
        public CargarResultadosMasivosRequestBody() {
        }
        
        public CargarResultadosMasivosRequestBody(System.Collections.Generic.List<Talentos_Master.ReportesReference.ResultadoFinalBE> lstResultados) {
            this.lstResultados = lstResultados;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CargarResultadosMasivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CargarResultadosMasivosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.CargarResultadosMasivosResponseBody Body;
        
        public CargarResultadosMasivosResponse() {
        }
        
        public CargarResultadosMasivosResponse(Talentos_Master.ReportesReference.CargarResultadosMasivosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CargarResultadosMasivosResponseBody {
        
        public CargarResultadosMasivosResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarMailResultadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarMailResultado", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.EnviarMailResultadoRequestBody Body;
        
        public EnviarMailResultadoRequest() {
        }
        
        public EnviarMailResultadoRequest(Talentos_Master.ReportesReference.EnviarMailResultadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarMailResultadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CodEvaluacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public EnviarMailResultadoRequestBody() {
        }
        
        public EnviarMailResultadoRequestBody(string CodEvaluacion, string token) {
            this.CodEvaluacion = CodEvaluacion;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarMailResultadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarMailResultadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.EnviarMailResultadoResponseBody Body;
        
        public EnviarMailResultadoResponse() {
        }
        
        public EnviarMailResultadoResponse(Talentos_Master.ReportesReference.EnviarMailResultadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EnviarMailResultadoResponseBody {
        
        public EnviarMailResultadoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularReporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularReporte", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.CalcularReporteRequestBody Body;
        
        public CalcularReporteRequest() {
        }
        
        public CalcularReporteRequest(Talentos_Master.ReportesReference.CalcularReporteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularReporteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DNI;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool administrador;
        
        public CalcularReporteRequestBody() {
        }
        
        public CalcularReporteRequestBody(string DNI, bool administrador) {
            this.DNI = DNI;
            this.administrador = administrador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalcularReporteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalcularReporteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.CalcularReporteResponseBody Body;
        
        public CalcularReporteResponse() {
        }
        
        public CalcularReporteResponse(Talentos_Master.ReportesReference.CalcularReporteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CalcularReporteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CalcularReporteResult;
        
        public CalcularReporteResponseBody() {
        }
        
        public CalcularReporteResponseBody(string CalcularReporteResult) {
            this.CalcularReporteResult = CalcularReporteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CuadroResultadoListarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CuadroResultadoListar", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.CuadroResultadoListarRequestBody Body;
        
        public CuadroResultadoListarRequest() {
        }
        
        public CuadroResultadoListarRequest(Talentos_Master.ReportesReference.CuadroResultadoListarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CuadroResultadoListarRequestBody {
        
        public CuadroResultadoListarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CuadroResultadoListarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CuadroResultadoListarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.CuadroResultadoListarResponseBody Body;
        
        public CuadroResultadoListarResponse() {
        }
        
        public CuadroResultadoListarResponse(Talentos_Master.ReportesReference.CuadroResultadoListarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CuadroResultadoListarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.CuadroResultadoBE> CuadroResultadoListarResult;
        
        public CuadroResultadoListarResponseBody() {
        }
        
        public CuadroResultadoListarResponseBody(System.Collections.Generic.List<Talentos_Master.ReportesReference.CuadroResultadoBE> CuadroResultadoListarResult) {
            this.CuadroResultadoListarResult = CuadroResultadoListarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultadosParticipantesImportarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultadosParticipantesImportar", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.ResultadosParticipantesImportarRequestBody Body;
        
        public ResultadosParticipantesImportarRequest() {
        }
        
        public ResultadosParticipantesImportarRequest(Talentos_Master.ReportesReference.ResultadosParticipantesImportarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadosParticipantesImportarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FechaInicio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FechaFin;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Empresa;
        
        public ResultadosParticipantesImportarRequestBody() {
        }
        
        public ResultadosParticipantesImportarRequestBody(string FechaInicio, string FechaFin, string Empresa) {
            this.FechaInicio = FechaInicio;
            this.FechaFin = FechaFin;
            this.Empresa = Empresa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultadosParticipantesImportarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultadosParticipantesImportarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Talentos_Master.ReportesReference.ResultadosParticipantesImportarResponseBody Body;
        
        public ResultadosParticipantesImportarResponse() {
        }
        
        public ResultadosParticipantesImportarResponse(Talentos_Master.ReportesReference.ResultadosParticipantesImportarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultadosParticipantesImportarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ResultadosParticipantesImportarResult;
        
        public ResultadosParticipantesImportarResponseBody() {
        }
        
        public ResultadosParticipantesImportarResponseBody(bool ResultadosParticipantesImportarResult) {
            this.ResultadosParticipantesImportarResult = ResultadosParticipantesImportarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsReporteSoapChannel : Talentos_Master.ReportesReference.wsReporteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcularReporteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CalcularReporteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuadroResultadoListarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CuadroResultadoListarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Talentos_Master.ReportesReference.CuadroResultadoBE> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Talentos_Master.ReportesReference.CuadroResultadoBE>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResultadosParticipantesImportarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ResultadosParticipantesImportarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsReporteSoapClient : System.ServiceModel.ClientBase<Talentos_Master.ReportesReference.wsReporteSoap>, Talentos_Master.ReportesReference.wsReporteSoap {
        
        private BeginOperationDelegate onBeginResultadoDelegate;
        
        private EndOperationDelegate onEndResultadoDelegate;
        
        private System.Threading.SendOrPostCallback onResultadoCompletedDelegate;
        
        private BeginOperationDelegate onBeginCargarResultadosMasivosDelegate;
        
        private EndOperationDelegate onEndCargarResultadosMasivosDelegate;
        
        private System.Threading.SendOrPostCallback onCargarResultadosMasivosCompletedDelegate;
        
        private BeginOperationDelegate onBeginEnviarMailResultadoDelegate;
        
        private EndOperationDelegate onEndEnviarMailResultadoDelegate;
        
        private System.Threading.SendOrPostCallback onEnviarMailResultadoCompletedDelegate;
        
        private BeginOperationDelegate onBeginCalcularReporteDelegate;
        
        private EndOperationDelegate onEndCalcularReporteDelegate;
        
        private System.Threading.SendOrPostCallback onCalcularReporteCompletedDelegate;
        
        private BeginOperationDelegate onBeginCuadroResultadoListarDelegate;
        
        private EndOperationDelegate onEndCuadroResultadoListarDelegate;
        
        private System.Threading.SendOrPostCallback onCuadroResultadoListarCompletedDelegate;
        
        private BeginOperationDelegate onBeginResultadosParticipantesImportarDelegate;
        
        private EndOperationDelegate onEndResultadosParticipantesImportarDelegate;
        
        private System.Threading.SendOrPostCallback onResultadosParticipantesImportarCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public wsReporteSoapClient() {
        }
        
        public wsReporteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsReporteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsReporteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsReporteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ResultadoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CargarResultadosMasivosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EnviarMailResultadoCompleted;
        
        public event System.EventHandler<CalcularReporteCompletedEventArgs> CalcularReporteCompleted;
        
        public event System.EventHandler<CuadroResultadoListarCompletedEventArgs> CuadroResultadoListarCompleted;
        
        public event System.EventHandler<ResultadosParticipantesImportarCompletedEventArgs> ResultadosParticipantesImportarCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Talentos_Master.ReportesReference.wsReporteSoap.BeginResultado(Talentos_Master.ReportesReference.ResultadoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginResultado(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginResultado(Talentos_Master.ReportesReference.ResultadoFinalBE obj, Talentos_Master.ReportesReference.TalentoComplexBE tal, System.AsyncCallback callback, object asyncState) {
            Talentos_Master.ReportesReference.ResultadoRequest inValue = new Talentos_Master.ReportesReference.ResultadoRequest();
            inValue.Body = new Talentos_Master.ReportesReference.ResultadoRequestBody();
            inValue.Body.obj = obj;
            inValue.Body.tal = tal;
            return ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).BeginResultado(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Talentos_Master.ReportesReference.ResultadoResponse Talentos_Master.ReportesReference.wsReporteSoap.EndResultado(System.IAsyncResult result) {
            return base.Channel.EndResultado(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndResultado(System.IAsyncResult result) {
            Talentos_Master.ReportesReference.ResultadoResponse retVal = ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).EndResultado(result);
        }
        
        private System.IAsyncResult OnBeginResultado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Talentos_Master.ReportesReference.ResultadoFinalBE obj = ((Talentos_Master.ReportesReference.ResultadoFinalBE)(inValues[0]));
            Talentos_Master.ReportesReference.TalentoComplexBE tal = ((Talentos_Master.ReportesReference.TalentoComplexBE)(inValues[1]));
            return this.BeginResultado(obj, tal, callback, asyncState);
        }
        
        private object[] OnEndResultado(System.IAsyncResult result) {
            this.EndResultado(result);
            return null;
        }
        
        private void OnResultadoCompleted(object state) {
            if ((this.ResultadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ResultadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ResultadoAsync(Talentos_Master.ReportesReference.ResultadoFinalBE obj, Talentos_Master.ReportesReference.TalentoComplexBE tal) {
            this.ResultadoAsync(obj, tal, null);
        }
        
        public void ResultadoAsync(Talentos_Master.ReportesReference.ResultadoFinalBE obj, Talentos_Master.ReportesReference.TalentoComplexBE tal, object userState) {
            if ((this.onBeginResultadoDelegate == null)) {
                this.onBeginResultadoDelegate = new BeginOperationDelegate(this.OnBeginResultado);
            }
            if ((this.onEndResultadoDelegate == null)) {
                this.onEndResultadoDelegate = new EndOperationDelegate(this.OnEndResultado);
            }
            if ((this.onResultadoCompletedDelegate == null)) {
                this.onResultadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnResultadoCompleted);
            }
            base.InvokeAsync(this.onBeginResultadoDelegate, new object[] {
                        obj,
                        tal}, this.onEndResultadoDelegate, this.onResultadoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Talentos_Master.ReportesReference.wsReporteSoap.BeginCargarResultadosMasivos(Talentos_Master.ReportesReference.CargarResultadosMasivosRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCargarResultadosMasivos(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCargarResultadosMasivos(System.Collections.Generic.List<Talentos_Master.ReportesReference.ResultadoFinalBE> lstResultados, System.AsyncCallback callback, object asyncState) {
            Talentos_Master.ReportesReference.CargarResultadosMasivosRequest inValue = new Talentos_Master.ReportesReference.CargarResultadosMasivosRequest();
            inValue.Body = new Talentos_Master.ReportesReference.CargarResultadosMasivosRequestBody();
            inValue.Body.lstResultados = lstResultados;
            return ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).BeginCargarResultadosMasivos(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Talentos_Master.ReportesReference.CargarResultadosMasivosResponse Talentos_Master.ReportesReference.wsReporteSoap.EndCargarResultadosMasivos(System.IAsyncResult result) {
            return base.Channel.EndCargarResultadosMasivos(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndCargarResultadosMasivos(System.IAsyncResult result) {
            Talentos_Master.ReportesReference.CargarResultadosMasivosResponse retVal = ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).EndCargarResultadosMasivos(result);
        }
        
        private System.IAsyncResult OnBeginCargarResultadosMasivos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.Generic.List<Talentos_Master.ReportesReference.ResultadoFinalBE> lstResultados = ((System.Collections.Generic.List<Talentos_Master.ReportesReference.ResultadoFinalBE>)(inValues[0]));
            return this.BeginCargarResultadosMasivos(lstResultados, callback, asyncState);
        }
        
        private object[] OnEndCargarResultadosMasivos(System.IAsyncResult result) {
            this.EndCargarResultadosMasivos(result);
            return null;
        }
        
        private void OnCargarResultadosMasivosCompleted(object state) {
            if ((this.CargarResultadosMasivosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CargarResultadosMasivosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CargarResultadosMasivosAsync(System.Collections.Generic.List<Talentos_Master.ReportesReference.ResultadoFinalBE> lstResultados) {
            this.CargarResultadosMasivosAsync(lstResultados, null);
        }
        
        public void CargarResultadosMasivosAsync(System.Collections.Generic.List<Talentos_Master.ReportesReference.ResultadoFinalBE> lstResultados, object userState) {
            if ((this.onBeginCargarResultadosMasivosDelegate == null)) {
                this.onBeginCargarResultadosMasivosDelegate = new BeginOperationDelegate(this.OnBeginCargarResultadosMasivos);
            }
            if ((this.onEndCargarResultadosMasivosDelegate == null)) {
                this.onEndCargarResultadosMasivosDelegate = new EndOperationDelegate(this.OnEndCargarResultadosMasivos);
            }
            if ((this.onCargarResultadosMasivosCompletedDelegate == null)) {
                this.onCargarResultadosMasivosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCargarResultadosMasivosCompleted);
            }
            base.InvokeAsync(this.onBeginCargarResultadosMasivosDelegate, new object[] {
                        lstResultados}, this.onEndCargarResultadosMasivosDelegate, this.onCargarResultadosMasivosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Talentos_Master.ReportesReference.wsReporteSoap.BeginEnviarMailResultado(Talentos_Master.ReportesReference.EnviarMailResultadoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEnviarMailResultado(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginEnviarMailResultado(string CodEvaluacion, string token, System.AsyncCallback callback, object asyncState) {
            Talentos_Master.ReportesReference.EnviarMailResultadoRequest inValue = new Talentos_Master.ReportesReference.EnviarMailResultadoRequest();
            inValue.Body = new Talentos_Master.ReportesReference.EnviarMailResultadoRequestBody();
            inValue.Body.CodEvaluacion = CodEvaluacion;
            inValue.Body.token = token;
            return ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).BeginEnviarMailResultado(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Talentos_Master.ReportesReference.EnviarMailResultadoResponse Talentos_Master.ReportesReference.wsReporteSoap.EndEnviarMailResultado(System.IAsyncResult result) {
            return base.Channel.EndEnviarMailResultado(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndEnviarMailResultado(System.IAsyncResult result) {
            Talentos_Master.ReportesReference.EnviarMailResultadoResponse retVal = ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).EndEnviarMailResultado(result);
        }
        
        private System.IAsyncResult OnBeginEnviarMailResultado(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string CodEvaluacion = ((string)(inValues[0]));
            string token = ((string)(inValues[1]));
            return this.BeginEnviarMailResultado(CodEvaluacion, token, callback, asyncState);
        }
        
        private object[] OnEndEnviarMailResultado(System.IAsyncResult result) {
            this.EndEnviarMailResultado(result);
            return null;
        }
        
        private void OnEnviarMailResultadoCompleted(object state) {
            if ((this.EnviarMailResultadoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EnviarMailResultadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EnviarMailResultadoAsync(string CodEvaluacion, string token) {
            this.EnviarMailResultadoAsync(CodEvaluacion, token, null);
        }
        
        public void EnviarMailResultadoAsync(string CodEvaluacion, string token, object userState) {
            if ((this.onBeginEnviarMailResultadoDelegate == null)) {
                this.onBeginEnviarMailResultadoDelegate = new BeginOperationDelegate(this.OnBeginEnviarMailResultado);
            }
            if ((this.onEndEnviarMailResultadoDelegate == null)) {
                this.onEndEnviarMailResultadoDelegate = new EndOperationDelegate(this.OnEndEnviarMailResultado);
            }
            if ((this.onEnviarMailResultadoCompletedDelegate == null)) {
                this.onEnviarMailResultadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEnviarMailResultadoCompleted);
            }
            base.InvokeAsync(this.onBeginEnviarMailResultadoDelegate, new object[] {
                        CodEvaluacion,
                        token}, this.onEndEnviarMailResultadoDelegate, this.onEnviarMailResultadoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Talentos_Master.ReportesReference.wsReporteSoap.BeginCalcularReporte(Talentos_Master.ReportesReference.CalcularReporteRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCalcularReporte(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCalcularReporte(string DNI, bool administrador, System.AsyncCallback callback, object asyncState) {
            Talentos_Master.ReportesReference.CalcularReporteRequest inValue = new Talentos_Master.ReportesReference.CalcularReporteRequest();
            inValue.Body = new Talentos_Master.ReportesReference.CalcularReporteRequestBody();
            inValue.Body.DNI = DNI;
            inValue.Body.administrador = administrador;
            return ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).BeginCalcularReporte(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Talentos_Master.ReportesReference.CalcularReporteResponse Talentos_Master.ReportesReference.wsReporteSoap.EndCalcularReporte(System.IAsyncResult result) {
            return base.Channel.EndCalcularReporte(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndCalcularReporte(System.IAsyncResult result) {
            Talentos_Master.ReportesReference.CalcularReporteResponse retVal = ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).EndCalcularReporte(result);
            return retVal.Body.CalcularReporteResult;
        }
        
        private System.IAsyncResult OnBeginCalcularReporte(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string DNI = ((string)(inValues[0]));
            bool administrador = ((bool)(inValues[1]));
            return this.BeginCalcularReporte(DNI, administrador, callback, asyncState);
        }
        
        private object[] OnEndCalcularReporte(System.IAsyncResult result) {
            string retVal = this.EndCalcularReporte(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCalcularReporteCompleted(object state) {
            if ((this.CalcularReporteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CalcularReporteCompleted(this, new CalcularReporteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CalcularReporteAsync(string DNI, bool administrador) {
            this.CalcularReporteAsync(DNI, administrador, null);
        }
        
        public void CalcularReporteAsync(string DNI, bool administrador, object userState) {
            if ((this.onBeginCalcularReporteDelegate == null)) {
                this.onBeginCalcularReporteDelegate = new BeginOperationDelegate(this.OnBeginCalcularReporte);
            }
            if ((this.onEndCalcularReporteDelegate == null)) {
                this.onEndCalcularReporteDelegate = new EndOperationDelegate(this.OnEndCalcularReporte);
            }
            if ((this.onCalcularReporteCompletedDelegate == null)) {
                this.onCalcularReporteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCalcularReporteCompleted);
            }
            base.InvokeAsync(this.onBeginCalcularReporteDelegate, new object[] {
                        DNI,
                        administrador}, this.onEndCalcularReporteDelegate, this.onCalcularReporteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Talentos_Master.ReportesReference.wsReporteSoap.BeginCuadroResultadoListar(Talentos_Master.ReportesReference.CuadroResultadoListarRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCuadroResultadoListar(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCuadroResultadoListar(System.AsyncCallback callback, object asyncState) {
            Talentos_Master.ReportesReference.CuadroResultadoListarRequest inValue = new Talentos_Master.ReportesReference.CuadroResultadoListarRequest();
            inValue.Body = new Talentos_Master.ReportesReference.CuadroResultadoListarRequestBody();
            return ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).BeginCuadroResultadoListar(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Talentos_Master.ReportesReference.CuadroResultadoListarResponse Talentos_Master.ReportesReference.wsReporteSoap.EndCuadroResultadoListar(System.IAsyncResult result) {
            return base.Channel.EndCuadroResultadoListar(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.Generic.List<Talentos_Master.ReportesReference.CuadroResultadoBE> EndCuadroResultadoListar(System.IAsyncResult result) {
            Talentos_Master.ReportesReference.CuadroResultadoListarResponse retVal = ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).EndCuadroResultadoListar(result);
            return retVal.Body.CuadroResultadoListarResult;
        }
        
        private System.IAsyncResult OnBeginCuadroResultadoListar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginCuadroResultadoListar(callback, asyncState);
        }
        
        private object[] OnEndCuadroResultadoListar(System.IAsyncResult result) {
            System.Collections.Generic.List<Talentos_Master.ReportesReference.CuadroResultadoBE> retVal = this.EndCuadroResultadoListar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCuadroResultadoListarCompleted(object state) {
            if ((this.CuadroResultadoListarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CuadroResultadoListarCompleted(this, new CuadroResultadoListarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CuadroResultadoListarAsync() {
            this.CuadroResultadoListarAsync(null);
        }
        
        public void CuadroResultadoListarAsync(object userState) {
            if ((this.onBeginCuadroResultadoListarDelegate == null)) {
                this.onBeginCuadroResultadoListarDelegate = new BeginOperationDelegate(this.OnBeginCuadroResultadoListar);
            }
            if ((this.onEndCuadroResultadoListarDelegate == null)) {
                this.onEndCuadroResultadoListarDelegate = new EndOperationDelegate(this.OnEndCuadroResultadoListar);
            }
            if ((this.onCuadroResultadoListarCompletedDelegate == null)) {
                this.onCuadroResultadoListarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCuadroResultadoListarCompleted);
            }
            base.InvokeAsync(this.onBeginCuadroResultadoListarDelegate, null, this.onEndCuadroResultadoListarDelegate, this.onCuadroResultadoListarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Talentos_Master.ReportesReference.wsReporteSoap.BeginResultadosParticipantesImportar(Talentos_Master.ReportesReference.ResultadosParticipantesImportarRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginResultadosParticipantesImportar(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginResultadosParticipantesImportar(string FechaInicio, string FechaFin, string Empresa, System.AsyncCallback callback, object asyncState) {
            Talentos_Master.ReportesReference.ResultadosParticipantesImportarRequest inValue = new Talentos_Master.ReportesReference.ResultadosParticipantesImportarRequest();
            inValue.Body = new Talentos_Master.ReportesReference.ResultadosParticipantesImportarRequestBody();
            inValue.Body.FechaInicio = FechaInicio;
            inValue.Body.FechaFin = FechaFin;
            inValue.Body.Empresa = Empresa;
            return ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).BeginResultadosParticipantesImportar(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Talentos_Master.ReportesReference.ResultadosParticipantesImportarResponse Talentos_Master.ReportesReference.wsReporteSoap.EndResultadosParticipantesImportar(System.IAsyncResult result) {
            return base.Channel.EndResultadosParticipantesImportar(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndResultadosParticipantesImportar(System.IAsyncResult result) {
            Talentos_Master.ReportesReference.ResultadosParticipantesImportarResponse retVal = ((Talentos_Master.ReportesReference.wsReporteSoap)(this)).EndResultadosParticipantesImportar(result);
            return retVal.Body.ResultadosParticipantesImportarResult;
        }
        
        private System.IAsyncResult OnBeginResultadosParticipantesImportar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string FechaInicio = ((string)(inValues[0]));
            string FechaFin = ((string)(inValues[1]));
            string Empresa = ((string)(inValues[2]));
            return this.BeginResultadosParticipantesImportar(FechaInicio, FechaFin, Empresa, callback, asyncState);
        }
        
        private object[] OnEndResultadosParticipantesImportar(System.IAsyncResult result) {
            bool retVal = this.EndResultadosParticipantesImportar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnResultadosParticipantesImportarCompleted(object state) {
            if ((this.ResultadosParticipantesImportarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ResultadosParticipantesImportarCompleted(this, new ResultadosParticipantesImportarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ResultadosParticipantesImportarAsync(string FechaInicio, string FechaFin, string Empresa) {
            this.ResultadosParticipantesImportarAsync(FechaInicio, FechaFin, Empresa, null);
        }
        
        public void ResultadosParticipantesImportarAsync(string FechaInicio, string FechaFin, string Empresa, object userState) {
            if ((this.onBeginResultadosParticipantesImportarDelegate == null)) {
                this.onBeginResultadosParticipantesImportarDelegate = new BeginOperationDelegate(this.OnBeginResultadosParticipantesImportar);
            }
            if ((this.onEndResultadosParticipantesImportarDelegate == null)) {
                this.onEndResultadosParticipantesImportarDelegate = new EndOperationDelegate(this.OnEndResultadosParticipantesImportar);
            }
            if ((this.onResultadosParticipantesImportarCompletedDelegate == null)) {
                this.onResultadosParticipantesImportarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnResultadosParticipantesImportarCompleted);
            }
            base.InvokeAsync(this.onBeginResultadosParticipantesImportarDelegate, new object[] {
                        FechaInicio,
                        FechaFin,
                        Empresa}, this.onEndResultadosParticipantesImportarDelegate, this.onResultadosParticipantesImportarCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Talentos_Master.ReportesReference.wsReporteSoap CreateChannel() {
            return new wsReporteSoapClientChannel(this);
        }
        
        private class wsReporteSoapClientChannel : ChannelBase<Talentos_Master.ReportesReference.wsReporteSoap>, Talentos_Master.ReportesReference.wsReporteSoap {
            
            public wsReporteSoapClientChannel(System.ServiceModel.ClientBase<Talentos_Master.ReportesReference.wsReporteSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginResultado(Talentos_Master.ReportesReference.ResultadoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Resultado", _args, callback, asyncState);
                return _result;
            }
            
            public Talentos_Master.ReportesReference.ResultadoResponse EndResultado(System.IAsyncResult result) {
                object[] _args = new object[0];
                Talentos_Master.ReportesReference.ResultadoResponse _result = ((Talentos_Master.ReportesReference.ResultadoResponse)(base.EndInvoke("Resultado", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCargarResultadosMasivos(Talentos_Master.ReportesReference.CargarResultadosMasivosRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CargarResultadosMasivos", _args, callback, asyncState);
                return _result;
            }
            
            public Talentos_Master.ReportesReference.CargarResultadosMasivosResponse EndCargarResultadosMasivos(System.IAsyncResult result) {
                object[] _args = new object[0];
                Talentos_Master.ReportesReference.CargarResultadosMasivosResponse _result = ((Talentos_Master.ReportesReference.CargarResultadosMasivosResponse)(base.EndInvoke("CargarResultadosMasivos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEnviarMailResultado(Talentos_Master.ReportesReference.EnviarMailResultadoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("EnviarMailResultado", _args, callback, asyncState);
                return _result;
            }
            
            public Talentos_Master.ReportesReference.EnviarMailResultadoResponse EndEnviarMailResultado(System.IAsyncResult result) {
                object[] _args = new object[0];
                Talentos_Master.ReportesReference.EnviarMailResultadoResponse _result = ((Talentos_Master.ReportesReference.EnviarMailResultadoResponse)(base.EndInvoke("EnviarMailResultado", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCalcularReporte(Talentos_Master.ReportesReference.CalcularReporteRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CalcularReporte", _args, callback, asyncState);
                return _result;
            }
            
            public Talentos_Master.ReportesReference.CalcularReporteResponse EndCalcularReporte(System.IAsyncResult result) {
                object[] _args = new object[0];
                Talentos_Master.ReportesReference.CalcularReporteResponse _result = ((Talentos_Master.ReportesReference.CalcularReporteResponse)(base.EndInvoke("CalcularReporte", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCuadroResultadoListar(Talentos_Master.ReportesReference.CuadroResultadoListarRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CuadroResultadoListar", _args, callback, asyncState);
                return _result;
            }
            
            public Talentos_Master.ReportesReference.CuadroResultadoListarResponse EndCuadroResultadoListar(System.IAsyncResult result) {
                object[] _args = new object[0];
                Talentos_Master.ReportesReference.CuadroResultadoListarResponse _result = ((Talentos_Master.ReportesReference.CuadroResultadoListarResponse)(base.EndInvoke("CuadroResultadoListar", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginResultadosParticipantesImportar(Talentos_Master.ReportesReference.ResultadosParticipantesImportarRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ResultadosParticipantesImportar", _args, callback, asyncState);
                return _result;
            }
            
            public Talentos_Master.ReportesReference.ResultadosParticipantesImportarResponse EndResultadosParticipantesImportar(System.IAsyncResult result) {
                object[] _args = new object[0];
                Talentos_Master.ReportesReference.ResultadosParticipantesImportarResponse _result = ((Talentos_Master.ReportesReference.ResultadosParticipantesImportarResponse)(base.EndInvoke("ResultadosParticipantesImportar", _args, result)));
                return _result;
            }
        }
    }
}
